#!/usr/bin/python3
import uuid
import datetime
import getpass
import os
import json


# increase reusability by assigning values to variables(Remove)
time = datetime.datetime.now().time().strftime("%H:%M:%S")
sys_user = getpass.getuser()

print("Time of execution is:", time )
print("Username is:",sys_user )

# Getting path of the folder to access user files(Remove)
PWD = os.getcwd()

#Dynamically add foleder name
folder_name = input("Enter your folder Name : ")

# Remove unwanted comments(Remove)
users_folder = PWD+"/"+folder_name
files_list = os.listdir(users_folder)

user_names_list = []

for file_name in files_list:
    with open(users_folder + file_name, 'r') as file:
        user_names_list.extend(file.readlines())  # Appending data of each file after unpacking(Remove)
        for user in user_names_list:
            user.strip()  # Removing new line character from each line(Remove)
user_names = [user.strip() for user in user_names_list]


# Generating universal unique ID for each user
def generate_uuid(user_names):
    """
    Add comments in doc string for a function
    """
    return user_names[0] + str(uuid.uuid1())


# Creating email_id for each user
def generate_email(user_names):
    """
    Add comments in doc string for a function
    """
    first_name, last_name = user_names.split()
    return first_name + last_name[:1] +"@email.com"


user_info = []
# collecting data in specified JSON format(Remove)
for user_name in user_names:
    user_info.append({generate_uuid(user_name): {"name": user_name, "email": generate_email(user_name)}})

# writing data to a JSON file format(Remove)
with open('user_data.json', 'w') as j:
    j.write(json.dumps(user_info))


# REVIEW

# Remove unwanted comments
# use variable assigments for values
# generated by core python modules for reusabilit
